// <auto-generated />
using System;
using CSupporter.Modules.Contractors.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSupporter.Modules.Contractors.Migrations
{
    [DbContext(typeof(CSupporterDbContext))]
    [Migration("20211028204753_AddMoreSampleContractor")]
    partial class AddMoreSampleContractor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSupporter.Modules.Contractors.Entities.Contractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contractors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("955fb204-a56d-43c6-8117-31fe22537483"),
                            Address = "Warszawa, ul. Przedszkolna 15",
                            CompanyDetails = "--",
                            CompanyName = "GM Prime RN",
                            FirstName = "Richard",
                            InsertDate = new DateTime(2021, 10, 28, 22, 47, 53, 31, DateTimeKind.Local).AddTicks(5685),
                            LastName = "Nowak",
                            NIP = "912-111-09-10",
                            UpdateDate = new DateTime(2021, 10, 28, 22, 47, 53, 31, DateTimeKind.Local).AddTicks(5821)
                        },
                        new
                        {
                            Id = new Guid("f6738f1f-5d8a-442c-8386-98668e83493d"),
                            Address = "Gdański, ul. Mariacka 8",
                            CompanyDetails = "--",
                            CompanyName = "FUH Adrian",
                            FirstName = "Adrian",
                            InsertDate = new DateTime(2021, 10, 28, 22, 47, 53, 35, DateTimeKind.Local).AddTicks(1793),
                            LastName = "Kowalski",
                            NIP = "805-111-09-10",
                            UpdateDate = new DateTime(2021, 10, 28, 22, 47, 53, 35, DateTimeKind.Local).AddTicks(1862)
                        },
                        new
                        {
                            Id = new Guid("f485167a-ff16-4a8c-83d5-1379a86ca8ff"),
                            Address = "Wrocław, ul. Żeromskiego 10",
                            CompanyDetails = "--",
                            CompanyName = "KOMFORT",
                            FirstName = "Roman",
                            InsertDate = new DateTime(2021, 10, 28, 22, 47, 53, 35, DateTimeKind.Local).AddTicks(2134),
                            LastName = "Romanowicz",
                            NIP = "712-934-35-23",
                            UpdateDate = new DateTime(2021, 10, 28, 22, 47, 53, 35, DateTimeKind.Local).AddTicks(2150)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
